# Generated by Django 5.1.15 on 2026-05-07 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaMensaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("recordatorio_pago", "Recordatorio de pago"),
                            ("reserva_expira", "Reserva por expirar"),
                            ("bienvenida", "Bienvenida"),
                            ("confirmacion_pago", "Confirmación de pago"),
                            ("seguimiento", "Seguimiento"),
                            ("personalizado", "Personalizado"),
                        ],
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "contenido",
                    models.TextField(
                        help_text="Usa variables como {{cliente_nombre}}, {{monto}}, {{fecha_vencimiento}}, etc.",
                        verbose_name="Contenido",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
            ],
            options={
                "verbose_name": "Plantilla de mensaje",
                "verbose_name_plural": "Plantillas de mensajes",
            },
        ),
        migrations.CreateModel(
            name="NotificacionEnviada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[("whatsapp", "WhatsApp"), ("sms", "SMS")],
                        default="whatsapp",
                        max_length=20,
                        verbose_name="Canal",
                    ),
                ),
                ("mensaje_enviado", models.TextField(verbose_name="Mensaje enviado")),
                (
                    "telefono_destino",
                    models.CharField(max_length=20, verbose_name="Teléfono destino"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("enviada", "Enviada"),
                            ("entregada", "Entregada"),
                            ("fallida", "Fallida"),
                            ("pendiente", "Pendiente"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "twilio_sid",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Twilio SID"
                    ),
                ),
                (
                    "error_detalle",
                    models.TextField(blank=True, verbose_name="Detalle de error"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="crm.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "plantilla",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="envios",
                        to="notificaciones.plantillamensaje",
                        verbose_name="Plantilla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación enviada",
                "verbose_name_plural": "Notificaciones enviadas",
                "ordering": ["-created_at"],
            },
        ),
    ]
