# Generated by Django 5.1.15 on 2026-05-07 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("terrenos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapaProyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                ("svg_data", models.TextField(verbose_name="Datos SVG del mapa")),
                (
                    "configuracion_colores",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Colores por estado: {'disponible': '#22c55e', 'reservado': '#f59e0b', 'vendido': '#ef4444'}",
                        verbose_name="Configuración de colores",
                    ),
                ),
                (
                    "ancho",
                    models.PositiveIntegerField(default=800, verbose_name="Ancho (px)"),
                ),
                (
                    "alto",
                    models.PositiveIntegerField(default=600, verbose_name="Alto (px)"),
                ),
                (
                    "proyecto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapa",
                        to="terrenos.proyecto",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapa de proyecto",
                "verbose_name_plural": "Mapas de proyectos",
            },
        ),
        migrations.CreateModel(
            name="CoordenadaLote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "svg_path",
                    models.TextField(
                        help_text="Coordenadas del polígono SVG que representa el lote en el mapa.",
                        verbose_name="Path SVG",
                    ),
                ),
                (
                    "lote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordenada_mapa",
                        to="terrenos.lote",
                        verbose_name="Lote",
                    ),
                ),
                (
                    "mapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordenadas",
                        to="mapa.mapaproyecto",
                        verbose_name="Mapa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coordenada de lote en mapa",
                "verbose_name_plural": "Coordenadas de lotes en mapa",
            },
        ),
    ]
