# Generated by Django 5.1.15 on 2026-05-07 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
        ("terrenos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="Número de cuota")),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto (Q)"
                    ),
                ),
                (
                    "monto_capital",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Capital (Q)",
                    ),
                ),
                (
                    "monto_interes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Interés (Q)",
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(verbose_name="Fecha de vencimiento"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("pagada", "Pagada"),
                            ("mora", "En mora"),
                            ("parcial", "Pago parcial"),
                        ],
                        db_index=True,
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "saldo_restante",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Saldo restante (Q)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuota",
                "verbose_name_plural": "Cuotas",
                "ordering": ["plan_pago", "numero"],
            },
        ),
        migrations.CreateModel(
            name="PlanPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "cuota_mensual",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Cuota mensual (Q)",
                    ),
                ),
                (
                    "total_cuotas",
                    models.PositiveIntegerField(verbose_name="Total de cuotas"),
                ),
                (
                    "saldo_pendiente",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Saldo pendiente (Q)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de pago",
                "verbose_name_plural": "Planes de pago",
            },
        ),
        migrations.CreateModel(
            name="Abono",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Monto abonado (Q)",
                    ),
                ),
                ("fecha_pago", models.DateField(verbose_name="Fecha de pago")),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("transferencia", "Transferencia bancaria"),
                            ("cheque", "Cheque"),
                            ("deposito", "Depósito bancario"),
                            ("otro", "Otro"),
                        ],
                        default="efectivo",
                        max_length=20,
                        verbose_name="Método de pago",
                    ),
                ),
                (
                    "comprobante",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="comprobantes/",
                        verbose_name="Comprobante",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="abonos_registrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "cuota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="abonos",
                        to="finanzas.cuota",
                        verbose_name="Cuota",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abono",
                "verbose_name_plural": "Abonos",
                "ordering": ["-fecha_pago"],
            },
        ),
        migrations.AddField(
            model_name="cuota",
            name="plan_pago",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cuotas",
                to="finanzas.planpago",
                verbose_name="Plan de pago",
            ),
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Precio de venta (Q)",
                    ),
                ),
                (
                    "enganche",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Enganche (Q)"
                    ),
                ),
                (
                    "plazo_meses",
                    models.PositiveIntegerField(verbose_name="Plazo (meses)"),
                ),
                (
                    "tasa_interes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Tasa de interés anual (%)",
                    ),
                ),
                ("fecha_venta", models.DateField(verbose_name="Fecha de venta")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activa", "Activa"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="activa",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventas",
                        to="crm.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "lote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venta",
                        to="terrenos.lote",
                        verbose_name="Lote",
                    ),
                ),
                (
                    "reserva",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="venta",
                        to="crm.reserva",
                        verbose_name="Reserva origen",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventas_realizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
                "ordering": ["-fecha_venta"],
            },
        ),
        migrations.AddField(
            model_name="planpago",
            name="venta",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_pago",
                to="finanzas.venta",
                verbose_name="Venta",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cuota",
            unique_together={("plan_pago", "numero")},
        ),
    ]
