# Generated by Django 5.1.15 on 2026-05-07 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
        ("finanzas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la plantilla"
                    ),
                ),
                (
                    "contenido_template",
                    models.TextField(
                        help_text="Usa variables como {{cliente_nombre}}, {{lote_numero}}, {{precio_venta}}, etc.",
                        verbose_name="Contenido de la plantilla",
                    ),
                ),
                (
                    "variables_requeridas",
                    models.JSONField(
                        default=list,
                        help_text="Lista de nombres de variables que se deben reemplazar en la plantilla.",
                        verbose_name="Variables requeridas",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
            ],
            options={
                "verbose_name": "Plantilla de contrato",
                "verbose_name_plural": "Plantillas de contratos",
            },
        ),
        migrations.CreateModel(
            name="DocumentoLegal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("dpi", "DPI"),
                            ("rtu", "RTU"),
                            ("promesa_cv", "Promesa de Compra-Venta"),
                            ("escritura", "Escritura"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to="documentos_legales/", verbose_name="Archivo"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descripción"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_legales",
                        to="crm.cliente",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento legal",
                "verbose_name_plural": "Documentos legales",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "numero_fel",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Número FEL"
                    ),
                ),
                (
                    "serie",
                    models.CharField(blank=True, max_length=50, verbose_name="Serie"),
                ),
                (
                    "numero_autorizacion",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Número de autorización",
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateTimeField(verbose_name="Fecha de emisión"),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto (Q)"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("emitida", "Emitida"),
                            ("anulada", "Anulada"),
                            ("error", "Error"),
                        ],
                        default="emitida",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("xml_fel", models.TextField(blank=True, verbose_name="XML FEL")),
                ("pdf_url", models.URLField(blank=True, verbose_name="URL del PDF")),
                (
                    "error_detalle",
                    models.TextField(blank=True, verbose_name="Detalle de error"),
                ),
                (
                    "abono",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facturas",
                        to="finanzas.abono",
                        verbose_name="Abono asociado",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas",
                        to="finanzas.venta",
                        verbose_name="Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
                "ordering": ["-fecha_emision"],
            },
        ),
    ]
