# Generated by Django 5.1.15 on 2026-05-07 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("terrenos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                (
                    "dpi",
                    models.CharField(max_length=20, unique=True, verbose_name="DPI"),
                ),
                (
                    "nit",
                    models.CharField(blank=True, max_length=20, verbose_name="NIT"),
                ),
                ("telefono", models.CharField(max_length=20, verbose_name="Teléfono")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="Dirección")),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "vendedor_asignado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clientes_asignados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vendedor asignado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["apellido", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "fecha_expiracion",
                    models.DateTimeField(verbose_name="Fecha de expiración"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activa", "Activa"),
                            ("concretada", "Concretada"),
                            ("expirada", "Expirada"),
                            ("cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="activa",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "enganche_acordado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Enganche acordado (Q)",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="crm.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="terrenos.lote",
                        verbose_name="Lote",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas_realizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SeguimientoCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "tipo_contacto",
                    models.CharField(
                        choices=[
                            ("llamada", "Llamada"),
                            ("whatsapp", "WhatsApp"),
                            ("visita", "Visita en campo"),
                            ("email", "Correo electrónico"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de contacto",
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "fecha_proximo_contacto",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Próximo contacto"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos",
                        to="crm.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seguimientos_realizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguimiento de cliente",
                "verbose_name_plural": "Seguimientos de clientes",
                "ordering": ["-created_at"],
            },
        ),
    ]
