# Generated by Django 5.1.15 on 2026-05-07 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=20, verbose_name="Número de lote"),
                ),
                (
                    "manzana",
                    models.CharField(blank=True, max_length=20, verbose_name="Manzana"),
                ),
                (
                    "medida_frente",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Medida frente (m)",
                    ),
                ),
                (
                    "medida_fondo",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Medida fondo (m)"
                    ),
                ),
                (
                    "area_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Área total (m²)"
                    ),
                ),
                (
                    "num_finca",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número de finca"
                    ),
                ),
                (
                    "folio",
                    models.CharField(blank=True, max_length=50, verbose_name="Folio"),
                ),
                (
                    "libro",
                    models.CharField(blank=True, max_length=50, verbose_name="Libro"),
                ),
                (
                    "precio_base",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Precio base (Q)"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("reservado", "Reservado"),
                            ("vendido", "Vendido"),
                        ],
                        db_index=True,
                        default="disponible",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "coordenadas_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitud",
                    ),
                ),
                (
                    "coordenadas_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Longitud",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote",
                "verbose_name_plural": "Lotes",
                "ordering": ["proyecto", "manzana", "numero"],
            },
        ),
        migrations.CreateModel(
            name="FotografiaLote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(upload_to="lotes/fotos/", verbose_name="Imagen"),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descripción"
                    ),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotografias",
                        to="terrenos.lote",
                        verbose_name="Lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fotografía de lote",
                "verbose_name_plural": "Fotografías de lotes",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del proyecto"
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(max_length=300, verbose_name="Ubicación"),
                ),
                (
                    "departamento",
                    models.CharField(
                        default="Petén", max_length=100, verbose_name="Departamento"
                    ),
                ),
                (
                    "municipio",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Municipio"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "coordenadas_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitud",
                    ),
                ),
                (
                    "coordenadas_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Longitud",
                    ),
                ),
                (
                    "area_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Área total (m²)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="lote",
            name="proyecto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lotes",
                to="terrenos.proyecto",
                verbose_name="Proyecto",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lote",
            unique_together={("proyecto", "manzana", "numero")},
        ),
    ]
